// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veriakzilvmxlzjvvnsm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlcmlha3ppbHZteGx6anZ2bnNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTA4MjIsImV4cCI6MjA2Nzc4NjgyMn0.sOL5pYJtYVX-icEDZLoZ_86ssHjNcfZm6Exjt0iY9nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});